### ISSUE TITLE
Add minifb?

### ISSUE THREAD

**Issue by Shadlock0133** [ocboogie/rust-graphics-crates#2]
It's similar to `pixels` but because it handles window creation it's IMO simpler to use, and has better support for older hardware than `pixels`.

**Comment by ocboogie** [comment]
Yeah minifb somehow went under my radar. I'll look into it.

**Comment by ocboogie** [comment]
Do you happen to know what backends it uses? It doesn't say in the README.

**Comment by Shadlock0133** [comment]
`pixels` readme [contains](https://github.com/parasyte/pixels#comparison-with-minifb) comparison with `minifb`, which mentions that `minifb` isn't hardware accelerated. So it probably just uses native APIs.
